---
name: logic-tasks
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - extra
  - mtl
  - QuickCheck >= 2.14
  - random
  - containers
  - hspec
  - minisat-solver
  - wl-pprint-text
  - parsec
  - text
  - output-monad
  - pretty-simple
  - latex-svg-image >= 0.2
  - bytestring
  - utf8-string
  - SHA
  - directory
  - math-functions

library:
  source-dirs: src
  exposed-modules:
    - LogicTasks.Formula
    - LogicTasks.Table
    - LogicTasks.Resolution
    - LogicTasks.Config
    - LogicTasks.Semantics.Fill
    - LogicTasks.Semantics.Pick
    - LogicTasks.Semantics.Decide
    - LogicTasks.Semantics.Max
    - LogicTasks.Semantics.Min
    - LogicTasks.Semantics.Step
    - LogicTasks.Semantics.Prolog
    - LogicTasks.Semantics.Resolve
    - LogicTasks.Printing
    - LogicTasks.Parsing
    - LogicTasks.Util
    - LogicTasks.Syntax.IllegalCnfs
    - LogicTasks.Syntax.IllegalFormulas
    - LogicTasks.Syntax.SimplestFormula
    - LogicTasks.Syntax.SubTreeSet
    - LogicTasks.Syntax.TreeToFormula
    - Tasks.SynTree.Config
    - Tasks.SynTree.Quiz
    - Tasks.SubTree.Config
    - Tasks.SubTree.Quiz
    - Tasks.LegalProposition.Config
    - Tasks.LegalProposition.PrintIllegal
    - Tasks.LegalProposition.PrintBracket
    - Tasks.LegalProposition.Quiz
    - Tasks.SuperfluousBrackets.Config
    - Tasks.SuperfluousBrackets.Parsing
    - Tasks.SuperfluousBrackets.PrintSuperfluousBrackets
    - Tasks.SuperfluousBrackets.Quiz
    - Tasks.LegalCNF.Config
    - Tasks.LegalCNF.Quiz
    - Tasks.LegalCNF.GenerateIllegal
    - Tasks.LegalCNF.GenerateLegal
    - Trees.Types
    - Trees.Parsing
    - Trees.Print
    - Trees.Helpers
    - Trees.Generate
    - Formula.Parsing
    - ParsingHelpers
    - Config
    - Formula.Types
    - Debug

  ghc-options:
    - -Wall
    - -Widentities
    - -fno-warn-unused-do-bind
    - -Werror
    - -Wwarn=incomplete-uni-patterns
    - -fdefer-typed-holes


tests:
  src-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
    dependencies:
      - logic-tasks
