{-# LANGUAGE RecordWildCards #-}

module Tasks.SynTree.Config (
  SynTreeConfig(..),
  SynTreeInst(..),
  checkSynTreeConfig,
  dSynTreeConfig,
  ) where

import Types (SynTree)
import Generate (rangeDepthForNodes, maxLeavesForNodes, maxNodesForDepth)

data SynTreeConfig =
  SynTreeConfig
  { maxnode :: Integer
  , minnode :: Integer
  , maxdepth :: Integer
  , electliteral :: String
  , mustcontain :: Integer
  ,useImplEqui::Bool
  } deriving Show

checkSynTreeConfig :: SynTreeConfig -> Maybe String
checkSynTreeConfig SynTreeConfig{..}
    | minnode < 1
      = Just "Minimal number of nodes must be positive."
    | maxnode < minnode
      = Just "Maximal number of nodes must not be smaller than minimal number."
    | maxdepth < 1
      = Just "Non-positive depth makes no sense."
    | mustcontain < 1
      = Just "At least one literal occurs in each formula."
    | fromIntegral (length electliteral) < mustcontain
      = Just "You have provided too few literals."
    | fst (rangeDepthForNodes minnode) > maxdepth
      = Just "The number of nodes generated at the specific depth is less than the minimum number of nodes"
    | maxLeavesForNodes maxnode < mustcontain
      = Just "The syntax tree generated by the maximum number of nodes cannot contain enough must contain Literals"
    | 2 ^ (maxdepth - 1) < mustcontain
      = Just "The syntax tree with maximum depth cannot contain enough must contain Literals"
    | minnode < mustcontain * 2 - 1
      = Just "Your minimum number of nodes does not permit enough leaves for all desired literals."
    | maxnode > maxNodesForDepth maxdepth
      = Just "Your minimum number of nodes is larger than what your maximum depth enables."
    | otherwise = Nothing

dSynTreeConfig :: SynTreeConfig
dSynTreeConfig =
  SynTreeConfig
  { maxnode = 10
  , minnode = 6
  , maxdepth = 6
  , electliteral = "ABCDE"
  , mustcontain = 3
  , useImplEqui = False
  }

data SynTreeInst =
  SynTreeInst
  { insSyntree :: SynTree Char
  , image :: String
  , correct :: String
  } deriving Show